### ISSUE TITLE
Possible improvements for user handling

### ISSUE THREAD

**Issue by Hendrik1704** [surmising/surmise#108]
Dear BAND team,

In our recent paper (https://arxiv.org/abs/2405.12019), where we compared different emulators, we used two emulators implemented in the surmise package. After some discussions with @mosesyhc via email I will give here a summary of the difficulties we had in the beginning.

The major difficulties, in the beginning, were the dimensionalities of the needed inputs and the interpretation of `x` and `theta`. Maybe this could be clarified with an example in the documentation.
After this was clear to us, the only problem was the formatting of the covariance matrix returned from the emulators, which has the shape `(num_observables, num_predictions, num_observables)`. This is not a very intuitive format for this matrix. I'd recommend using `(num_predictions,  num_observables, num_observables)` as an output format.

Kind regards,
Hendrik Roch

**Comment by mosesyhc** [comment]
> The major difficulties, in the beginning, were the dimensionalities of the needed inputs and the interpretation of x and theta. Maybe this could be clarified with an example in the documentation.

- [x] The updated documentation will include a full example for reference.

> After this was clear to us, the only problem was the formatting of the covariance matrix returned from the emulators, which has the shape (num_observables, num_predictions, num_observables). This is not a very intuitive format for this matrix. I'd recommend using (num_predictions,  num_observables, num_observables) as an output format.

Thanks for the suggestion! We are looking into including the switch in #118.
